# Generated by Django 5.0.1 on 2024-01-28 03:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A Client with that name already exists.'}, help_text='Required. 150 characters or fewer.', max_length=150, unique=True, verbose_name='Client Name')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A Database with that name already exists.'}, help_text='Required. 150 characters or fewer.', max_length=150, unique=True, verbose_name='Database Name')),
                ('description', models.CharField(help_text='200 characters or fewer.', max_length=200, verbose_name='Database Name')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(help_text='200 characters or fewer.', max_length=200, on_delete=django.db.models.deletion.RESTRICT, to='core.businessclient', verbose_name='Company Name')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A project with that name already exists.'}, help_text='Required. 150 characters or fewer.', max_length=150, unique=True, verbose_name='Project Name')),
                ('description', models.CharField(help_text='200 characters or fewer.', max_length=200, verbose_name='Database Name')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
