# Generated by Django 5.0.1 on 2024-01-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businessclient_database_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_client',
            field=models.ForeignKey(default=1, help_text='Required. 50 characters or fewer.', max_length=50, on_delete=django.db.models.deletion.RESTRICT, to='core.businessclient', verbose_name='Client Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='database',
            field=models.ForeignKey(default=1, help_text='Required. 50 characters or fewer.', max_length=50, on_delete=django.db.models.deletion.RESTRICT, to='core.database', verbose_name='Database Name'),
            preserve_default=False,
        ),
    ]
