# Generated by Django 5.0.1 on 2024-01-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_business_client_project_database'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='business_client',
            new_name='client',
        ),
    ]
