---
name: Checks

# This is the trigger that we want to run when a push occurs
on:
  push:
    branches: main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04 #ubuntu version that has docker installed on the image
    steps:
      - name: Login to Docker Hub #GitHub Action to login against a Docker registry
        uses: docker/login-action@v3 #https://github.com/docker/login-action
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout #This action checks-out your repository, so your workflow can access it.
        uses: actions/checkout@v4 #https://github.com/actions/checkout
      - name: Test # Run unit tests on our project
        run: docker-compose run --rm app sh -c "coverage run manage.py test" # Command that will run the unit tests
      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Lint # Perform linting check on the project
        run: docker-compose run --rm app sh -c "flake8"
